### ISSUE TITLE
PHP 8.0.0RC5 + mysqli error: `Uncaught TypeError: mysqli_num_rows()`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1579]
### Expected behaviour

Error-free front side.

### Actual behaviour

```
Error: Fatal error: Uncaught TypeError: mysqli_num_rows(): Argument #1 ($result) must be of type mysqli_result, bool given in /var/www/sites/textpattern.co/php-next-dev-demo/live/4.8.4/textpattern/lib/txplib_db.php:869 Stack trace: #0 /var/www/sites/textpattern.co/php-next-dev-demo/live/4.8.4/textpattern/lib/txplib_db.php(869): mysqli_num_rows() #1 /var/www/sites/textpattern.co/php-next-dev-demo/live/4.8.4/textpattern/lib/txplib_misc.php(3333): safe_field() #2 /var/www/sites/textpattern.co/php-next-dev-demo/live/4.8.4/textpattern/lib/txplib_misc.php(3363): fetch_page() #3 /var/www/sites/textpattern.co/php-next-dev-demo/live/4.8.4/textpattern/publish.php(740): parse_page() #4 /var/www/sites/textpattern.co/php-next-dev-demo/live/4.8.4/index.php(74): textpattern() #5 {main} thrown in /var/www/sites/textpattern.co/php-next-dev-demo/live/4.8.4/textpattern/lib/txplib_db.php on line 869
```

### Steps to reproduce

* install `4.8.4` branch via auto-installer
* note error

#### Additional information

Textpattern version: `4.8.4` branch

Web server vendor and version: Nginx 1.19.4

Database server vendor and version: Percona 8.0

PHP version: PHP 8.0.0 RC5

Error found at https://php-next-dev-demo.textpattern.co/4.8.4/

**Comment by petecooper** [comment]
Fixed with https://github.com/textpattern/textpattern/commit/02163eddfa4775e835d43fac350d14fc1aba3c0c
