### ISSUE TITLE
theme `name` white space characters

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1826]
The theme `name` field should not accept white space characters (U+0020, U+00A0, …). When first time saving, convert those to hyphen (U+002D) or underscore, similar to e.g. category name.

More details in this [forum thread](https://forum.textpattern.com/viewtopic.php?id=51896).

**Comment by phiw13** [comment]
BTW, the placeholder string in the error message is `skin_unsafe_name`, but there is no such item in the lang_name.ini files. There is:

```
skin_name_invalid="…"
skin_name_unsafe="Not exportable theme names for: <strong>{list}</strong>. Names must match the following regular expression: <code>^[a-z][a-z0-9_\-\.]{0,63}$</code>."
```

**Comment by Bloke** [comment]
Darnit. Wrong string ref in the code. I'll fix that.

**Comment by Bloke** [comment]
I've hopefully trapped regular spaces, tabs(?) and nbsp in e4cb82f, and converted them to underscores. This also affects Page, Form and Stylesheet names so please check it works okay and only affects the name field.

**Comment by phiw13** [comment]
Testing on the Themes panel - Create new Theme
* space - yes, converted to underscore.
* nbsp – rather problematic here * see below
* tab – hard to do in an single line input field :-), but copy-paste from text editor: the browser seems to swallow it on submit (?). Anyway, `foo[tab]bar` is converted to `foobar`
* a Chinese/Japanese space (IDEOGRAPHIC SPACE or U+3000) is accepted – but then any CJK character in the `name` field is accepted and causing a failure when trying to export to the file system.

I did not try other “space”  type characters, most are rather difficult to input directly from the keyboard anyway.

-^-
the no-break space, input: option + spacebar (NO-BREAK SPACE, or `&nbsp;` or as UTF8hex: 0xC2A0):

input: test[no-break space]a

On localhost with MySql8.0.x, on a Live server with MariaDB 10.6.x and on Pete’s demo server, I get this uggggly MySql error:

```
Fatal error: Uncaught mysqli_sql_exception: Incorrect string value: '\xC2_a' for column `lcn_domain`.`txp_skin`.`name` at row 1 in /home/username/apps/domain/textpattern/lib/txplib_db.php:442 Stack trace: #0 /home/username/apps/domain/textpattern/lib/txplib_db.php(442): mysqli_query() #1 /home/username/apps/domain/textpattern/lib/txplib_db.php(527): safe_query() #2 /home/username/apps/domain/textpattern/vendors/Textpattern/Skin/CommonBase.php(523): safe_insert() #3 /home/username/apps/domain/textpattern/vendors/Textpattern/Skin/Skin.php(510): Textpattern\Skin\CommonBase->createRow() #4 /home/username/apps/domain/textpattern/vendors/Textpattern/Skin/Skin.php(1019): Textpattern\Skin\Skin->create() #5 /home/username/apps/domain/textpattern/include/txp_skin.php(31): Textpattern\Skin\Skin->admin() #6 /home/username/apps/domain/textpattern/index.php(232): include('...') #7 {main} thrown in /home/username/apps/domain/textpattern/lib/txplib_db.php on line 442
```

–^–

On the Forms & Pages panel, with a new form, same string as above, I get the same message.

**Comment by Bloke** [comment]
Thanks for testing. In which case, we need to do more here to defend against such characters. Leave it with me.

**Comment by phiw13** [comment]
Yeah, there are - as far exporting to the file system is concerned – quite a few problems. People who uses  anything outside of ASCII are bound to run into problems. Diacritics of all kind (French, Vietnamese), all kind of Asian languages (character sets), or ancient Phoenician or… (I don’t think Linear-A is included in Unicode yet). Those work internally in Textpattern, as far as I know, but the file system might have problems.

Possible option 1: tighten the pop-help for those fields. Currently for the Theme `name` it _suggests_ “The name shouldn’t contain any special characters or spaces.” That is pretty vague…

Possible option 2: use the `pattern` attribute on those name fields with a ASCII regular expression – but that is not backwards compatible.

(what are “special characters” ?)
