### ISSUE TITLE
Error thrown with current Textile

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1851]
Using the auto-installer on the `dev` demo:

```
PHP Fatal error:  Uncaught Error: Class "Netcarver\Textile\Parser" not found in /var/www/servers/textpattern.co/dev-demo/live/dev/textpattern/vendors/Textpattern/Import/TxpXML.php:143
Stack trace:
#0 /var/www/servers/textpattern.co/dev-demo/live/dev/textpattern/vendors/Textpattern/Import/TxpXML.php(124): Textpattern\Import\TxpXML->importXmlArticles()
#1 /var/www/servers/textpattern.co/dev-demo/live/dev/textpattern/setup/setup_lib.php(170): Textpattern\Import\TxpXML->importXml()
#2 /var/www/servers/textpattern.co/dev-demo/live/dev/textpattern/setup/setup.php(106): setup_db()
#3 {main}
  thrown in /var/www/servers/textpattern.co/dev-demo/live/dev/textpattern/vendors/Textpattern/Import/TxpXML.php on line 143

Fatal error: Uncaught Error: Class "Netcarver\Textile\Parser" not found in /var/www/servers/textpattern.co/dev-demo/live/dev/textpattern/vendors/Textpattern/Import/TxpXML.php:143
Stack trace:
#0 /var/www/servers/textpattern.co/dev-demo/live/dev/textpattern/vendors/Textpattern/Import/TxpXML.php(124): Textpattern\Import\TxpXML->importXmlArticles()
#1 /var/www/servers/textpattern.co/dev-demo/live/dev/textpattern/setup/setup_lib.php(170): Textpattern\Import\TxpXML->importXml()
#2 /var/www/servers/textpattern.co/dev-demo/live/dev/textpattern/setup/setup.php(106): setup_db()
#3 {main}
  thrown in /var/www/servers/textpattern.co/dev-demo/live/dev/textpattern/vendors/Textpattern/Import/TxpXML.php on line 143
```

**Comment by petecooper** [comment]
Paging @bloatware re: https://forum.textpattern.com/viewtopic.php?pid=334246#p334246

**Comment by philwareham** [comment]
Probably an error on my part - missed the uppercase when I did the revert. Will fix this morning.

**Comment by philwareham** [comment]
Should be fixed now - please report.

**Comment by petecooper** [comment]
Fixed. Thanks @philwareham!
