### ISSUE TITLE
Admin -> Users throws `Uncaught mysqli_sql_exception: Unknown column` error on `dev`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1881]
### Expected behaviour

When visiting Admin -> Users, I expect the users to be listed, per release version.

### Actual behaviour

I don't see the users listed, I see the following error:

```
Fatal error: Uncaught mysqli_sql_exception: Unknown column 'dev_txp_users.name' in 'on clause' in /var/www/servers/textpattern.co/dev-demo/live/dev/textpattern/lib/txplib_db.php:442
Stack trace:
#0 /var/www/servers/textpattern.co/dev-demo/live/dev/textpattern/lib/txplib_db.php(442): mysqli_query()
#1 /var/www/servers/textpattern.co/dev-demo/live/dev/textpattern/lib/txplib_db.php(1283): safe_query()
#2 /var/www/servers/textpattern.co/dev-demo/live/dev/textpattern/include/txp_admin.php(467): getThing()
#3 /var/www/servers/textpattern.co/dev-demo/live/dev/textpattern/include/txp_admin.php(64): author_list()
#4 /var/www/servers/textpattern.co/dev-demo/live/dev/textpattern/index.php(232): include('...')
#5 {main} thrown in /var/www/servers/textpattern.co/dev-demo/live/dev/textpattern/lib/txplib_db.php on line 442
```

### Steps to reproduce

* Visit https://dev-demo.textpattern.co/dev/textpattern/index.php?event=admin
* Note error

Note this Textpattern instance uses a database prefix, and the auto installer. The .json is as follows (credentials removed):

```
{
	"site": {
		"language_code": "en",
		"public_url": "dev-demo.textpattern.co/dev",
		"admin_url": "",
		"admin_theme": "",
		"public_theme": "four-point-nine",
		"content_directory": "",
		"cookie_domain": ""
	},
	"database": {
		"user": "dev_demo",
		"password": "•••",
		"host": "127.0.0.1",
		"db_name": "dev_demo",
		"charset": "utf8mb4",
		"table_prefix": "dev_",
		"client_flags": ""
	},
	"user": {
		"full_name": "Textpattern Demo Robot",
		"email": "domo-arigato-mr-roboto@example.com",
		"login_name": "textpattern-robot",
		"password": "***"
	}
}
```

#### Additional information

Textpattern version: `4.9.0-dev`

Web server vendor and version: Nginx 1.25.1

Database server vendor and version: Percona Server

PHP version: 8.2.8

Operating system: Ubuntu 20.04

**Comment by petecooper** [comment]
Nice one @Bloke – thank you very much
