### ISSUE TITLE
Error when accessing Preferences panel

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1888]
```
Fatal error: Uncaught TypeError: strpos(): Argument #1 ($haystack) must be of type string, array given in /Users/username/Sites/txp_dev/textpattern/include/txp_prefs.php:374 
Stack trace: 
#0 /Users/username/Sites/txp_dev/textpattern/include/txp_prefs.php(374): strpos(Array, '\\') 
#1 /Users/username/Sites/txp_dev/textpattern/include/txp_prefs.php(285): pref_func(Array, 'smd_textile_bar...', 'shortcode', Array) 
#2 /Users/username/Sites/txp_dev/textpattern/include/txp_prefs.php(49): prefs_list() 
#3 /Users/username/Sites/txp_dev/textpattern/index.php(232): include('/Users/username/S...') 
#4 {main} thrown in /Users/username/Sites/txp_dev/textpattern/include/txp_prefs.php on line 374
```

So far I can only reproduce this with the smd_textile_bar plugin installed and active. Other plugins might have the same problem, perhaps (or perhaps it is specific to this plugin?).

The cause might be this commit: https://github.com/textpattern/textpattern/commit/1d5887bf6a50b2200acd795acbc451fc3618d0c6

**Comment by Bloke** [comment]
Ack, good catch. Fixed in 9b632e94. Thank you.
