### ISSUE TITLE
Edit file / missing file: SQL error and warning when pressing ‘save’

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1907]
File Condition: missing
Open the Edit File panel, try to replace the missing file with an existing one from the file system,
Save

actual result: nothing is saved, the user is greeted with an error message.

```
Warning "filesize(): stat failed for /Users/[username]/Sites/_txp-dev/files/sq-green-400.afdesign"
in /Users/[username]/Sites/_txp-dev/textpattern/include/txp_file.php at line 1207.
adminErrorHandler()
textpattern/include/txp_file.php:1207 filesize()
textpattern/include/txp_file.php:69 file_save()
textpattern/index.php:218 include()

Fatal error: Uncaught mysqli_sql_exception: Incorrect integer value: '' for column 'size' at row 1 in /Users/[username]/Sites/_txp-dev/textpattern/lib/txplib_db.php:442 Stack trace: #0 /Users/[username]/Sites/_txp-dev/textpattern/lib/txplib_db.php(442): mysqli_query(Object(mysqli), 'UPDATE txp_file...', 0) #1 /Users/[username]/Sites/_txp-dev/textpattern/lib/txplib_db.php(503): safe_query('UPDATE txp_file...', false) #2 /Users/[username]/Sites/_txp-dev/textpattern/include/txp_file.php(1219): safe_update('txp_file', '\n filena...', 'id = '3'') #3 /Users/[username]/Sites/_txp-dev/textpattern/include/txp_file.php(69): file_save() #4 /Users/[username]/Sites/_txp-dev/textpattern/index.php(218): include('/Users/[username]/S...') #5 {main} thrown in /Users/[username]/Sites/_txp-dev/textpattern/lib/txplib_db.php on line 442

```

MySQL 8.0.28 / PHP 8.3 / TXP 4.9-dev latest.

**Comment by bloatware** [comment]
This should be fixed now, though I'm not sure how to handle the file name when replacing with an existing file.
