### ISSUE TITLE
Fatal error with new 4.6-dev installation

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#683]
New install, fresh download, empty database (i.e., no previous content or upgrade shenanigans) -- I get this immediately after providing Textpattern user details:

```
Fatal error: Uncaught Error: Call to undefined function xml_parser_create() in /var/www/vhosts/example.com/www/live/textpattern/lib/IXRClass.php:237 Stack trace: #0 /var/www/vhosts/example.com/www/live/textpattern/lib/IXRClass.php(756): IXR_Message->parse() #1 /var/www/vhosts/example.com/www/live/textpattern/setup/txpsql.php(578): IXR_Client->query('tups.getLanguag...', '0879796071e5be5...', 'en-gb') #2 /var/www/vhosts/example.com/www/live/textpattern/setup/index.php(682): include('/var/www/vhosts...') #3 /var/www/vhosts/example.com/www/live/textpattern/setup/index.php(94): createTxp() #4 {main} thrown in /var/www/vhosts/example.com/www/live/textpattern/lib/IXRClass.php on line 237
```

PHP 7.0.4, MySQL is Percona 5.6.22-71.0, Apache 2.4.18. Installation appears to have run OK as front end displays standard content. Logging in throws two errors, the first immediately after providing valid details:

```
Fatal error: Uncaught Error: Call to undefined function xml_parser_create() in /var/www/vhosts/example.com/www/live/textpattern/lib/IXRClass.php:237 Stack trace: #0 /var/www/vhosts/example.com/www/live/textpattern/lib/IXRClass.php(756): IXR_Message->parse() #1 /var/www/vhosts/example.com/www/live/textpattern/include/txp_lang.php(118): IXR_Client->query('tups.listLangua...', '4f4ec8ec75008e2...') #2 /var/www/vhosts/example.com/www/live/textpattern/include/txp_lang.php(49): list_languages() #3 /var/www/vhosts/example.com/www/live/textpattern/index.php(211): include('/var/www/vhosts...') #4 {main} thrown in /var/www/vhosts/example.com/www/live/textpattern/lib/IXRClass.php on line 237
```

Refreshing the page throws this error:

```
Fatal error: Uncaught Error: Call to undefined function utf8_decode() in /var/www/vhosts/example.com/www/live/textpattern/lib/txplib_forms.php:205 Stack trace: #0 /var/www/vhosts/example.com/www/live/textpattern/include/txp_article.php(1357): treeSelectInput('Category1', Array, '', 'category-1', 35) #1 /var/www/vhosts/example.com/www/live/textpattern/include/txp_article.php(2017): category_popup('Category1', '', 'category-1') #2 /var/www/vhosts/example.com/www/live/textpattern/include/txp_article.php(917): article_partial_categories(Array, 'categories') #3 /var/www/vhosts/example.com/www/live/textpattern/include/txp_article.php(123): article_edit() #4 /var/www/vhosts/example.com/www/live/textpattern/index.php(211): include('/var/www/vhosts...') #5 {main} thrown in /var/www/vhosts/example.com/www/live/textpattern/lib/txplib_forms.php on line 205
```

**Comment by petecooper** [comment]
Mea culpa, broken PHP module install: http://forum.textpattern.com/viewtopic.php?pid=298890#p298890

**Comment by johnstephens** [comment]
This came up on my Vagrant server too. The answer was to install php7.0-xml in my bootstrap script:

```
sudo apt-get update
sudo apt-get install php7.0-xml
sudo service apache2 restart
```
